import { Patient } from '@/types/patient';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    civilite: 'Monsieur',
    gender: 'M',
    nom: 'EL AMRANI',
    prenom: 'Karim',
    telephone: '0661234567',
    cin: 'BK654321',
    age: 34,
    profession: 'Ingénieur Informatique',
    adresse: 'Résidence Al Manar, Casablanca',
    medecin_traitant: 'Dr. Benjelloun (Traumatologue)',
    assurance: 'CNSS',
    motif_consultation: 'Rééducation du genou droit suite rupture LCA (post-op)',
    antecedents: 'Chirurgie ligamentoplastie genou droit (M+1)',
    nombre_seances_prescrites: 20,
    nombre_seances_effectuees: 8,
    statut: 'Actif',
    notes: 'Bonne progression de la flexion (110°). Renforcement quadriceps en cours.',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'pat-2',
    civilite: 'Madame',
    gender: 'F',
    nom: 'BENNANI',
    prenom: 'Fatima Zahra',
    telephone: '0662987654',
    cin: 'BE879102',
    age: 48,
    profession: 'Enseignante',
    adresse: 'Quartier Palmier, Casablanca',
    medecin_traitant: 'Dr. Tazi (Rhumatologue)',
    assurance: 'CNOPS',
    motif_consultation: 'Cervico-brachialgie droite & tensions trapèzes',
    antecedents: 'Hernie discale C5-C6 non opérée',
    nombre_seances_prescrites: 12,
    nombre_seances_effectuees: 10,
    statut: 'Actif',
    notes: 'Diminution nette des paresthésies. Poursuivre étirements cervicaux.',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'pat-3',
    civilite: 'Monsieur',
    gender: 'M',
    nom: 'TAZI',
    prenom: 'Omar',
    telephone: '0663456789',
    cin: 'A456789',
    age: 62,
    profession: 'Retraité',
    adresse: 'Bourgogne, Casablanca',
    medecin_traitant: 'Dr. Chraibi (Chirurgien Orthopédiste)',
    assurance: 'AMO',
    motif_consultation: 'Prothèse totale de hanche gauche (PTH)',
    antecedents: 'Hypertension artérielle sous traitement',
    nombre_seances_prescrites: 15,
    nombre_seances_effectuees: 4,
    statut: 'Actif',
    notes: 'Travail de la marche sans canne anglaise. Bonne stabilité.',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: 'pat-4',
    civilite: 'Mademoiselle',
    gender: 'F',
    nom: 'MANSOURI',
    prenom: 'Sanaa',
    telephone: '0671122334',
    cin: 'BL987123',
    age: 29,
    profession: 'Comptable',
    adresse: 'Maârif, Casablanca',
    medecin_traitant: 'Dr. Alami (Généraliste)',
    assurance: 'Assurance Privée',
    motif_consultation: 'Lombalgie aiguë suite à un faux mouvement',
    antecedents: 'Scoliose idiopathique dorso-lombaire',
    nombre_seances_prescrites: 10,
    nombre_seances_effectuees: 10,
    statut: 'Terminé',
    notes: 'Séances complétées avec succès. Plus de douleur en position assise.',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'pat-5',
    civilite: 'Monsieur',
    gender: 'M',
    nom: 'IDRISSI',
    prenom: 'Mehdi',
    telephone: '0665554433',
    cin: 'D342156',
    age: 22,
    profession: 'Étudiant & Athlète',
    adresse: 'Ain Diab, Casablanca',
    medecin_traitant: 'Dr. Naciri (Médecin du Sport)',
    assurance: 'Aucune',
    motif_consultation: 'Entorse grave cheville droite (stade II)',
    antecedents: 'Entorses récidivantes cheville externe',
    nombre_seances_prescrites: 12,
    nombre_seances_effectuees: 3,
    statut: 'Actif',
    notes: 'Travail proprioceptif sur plateau de Freeman et réathlétisation.',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  }
];

export const TODAY_APPOINTMENTS = [
  {
    id: 'apt-1',
    heure: '09:00 - 09:45',
    patientNom: 'EL AMRANI Karim',
    pathologie: 'Rééducation LCA Genou',
    type: 'Salle de mécanothérapie',
    statut: 'Terminé',
    avatarBg: 'bg-emerald-500',
  },
  {
    id: 'apt-2',
    heure: '10:00 - 10:45',
    patientNom: 'BENNANI Fatima Zahra',
    pathologie: 'Cervicalgie & Trapèzes',
    type: 'Massage & Physiothérapie',
    statut: 'En cours',
    avatarBg: 'bg-blue-500',
  },
  {
    id: 'apt-3',
    heure: '11:15 - 12:00',
    patientNom: 'TAZI Omar',
    pathologie: 'PTH Hanche gauche',
    type: 'Rééducation à la marche',
    statut: 'Confirmé',
    avatarBg: 'bg-purple-500',
  },
  {
    id: 'apt-4',
    heure: '14:30 - 15:15',
    patientNom: 'IDRISSI Mehdi',
    pathologie: 'Entorse Cheville',
    type: 'Proprioception & Renforcement',
    statut: 'Confirmé',
    avatarBg: 'bg-amber-500',
  },
  {
    id: 'apt-5',
    heure: '16:00 - 16:45',
    patientNom: 'BERRADA Amine',
    pathologie: 'Bilan Kinésithérapique initial',
    type: 'Première consultation',
    statut: 'Confirmé',
    avatarBg: 'bg-rose-500',
  }
];
